const PATHS = {
    STREET: '/STREET',
    PORTRAIT: '/PORTRAIT',
    TRAVEL: '/TRAVEL',
    MOON: '/MOON',
    COMPOSITION: '/COMPOSITION',
    BIRDS: '/BIRDS',
    GEOMETRY: '/GEOMETRY',
    MANIPULATION: '/MANIPULATION',
    LANDSCAPE: '/LANDSCAPE',
    ARCHITECTURE: '/ARCHITECTURE'
};

export {PATHS};